INSERT INTO products (
    name, description, sku, price, category, stock_quantity, active,
    artisan_name, origin_town, origin_state, craft_type, image_url, rating
) VALUES
(
    'Channapatna Hand-turned Wooden Stacking Toy',
    'Certified GI craft made from seasoned Hale wood using natural vegetable dyes and shellac polish. Safe for toddlers and sustainably hand-turned on traditional foot-lathes by generational toy makers.',
    'CHN-WOOD-001',
    899.00,
    'woodcraft',
    35,
    TRUE,
    'Somanna Gowda (National Awardee)',
    'Channapatna',
    'Karnataka',
    'Woodcraft & Toys',
    'https://images.unsplash.com/photo-1558060370-d644479cb6f7?auto=format&fit=crop&w=800&q=80',
    4.90
),
(
    'Jaipur Royal Cobalt Blue Pottery Floral Vase',
    'Distinctive quartz and glass-based ceramic pottery handpainted in signature turquoise and cobalt blue Persian floral motifs. Fired once at low temperature without using any clay.',
    'JAI-POT-002',
    1450.00,
    'pottery',
    20,
    TRUE,
    'Kripal Kumbhar Collective',
    'Jaipur',
    'Rajasthan',
    'Ceramics & Pottery',
    'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    4.85
),
(
    'Varanasi Handloom Banarasi Katan Silk Dupatta',
    'Woven with pure mulberry silk yarns and real silver zari threads on pit-looms over 18 days. Features intricate kadhwa floral bootas and timeless Mughal paisleys.',
    'BSN-SILK-003',
    3499.00,
    'textiles',
    15,
    TRUE,
    'Noor Mohammad & Family',
    'Varanasi',
    'Uttar Pradesh',
    'Handloom & Weaving',
    'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    4.95
),
(
    'Bastar Dhokra Lost-Wax Bell Metal Nandi',
    'Ancient 4,000-year-old non-ferrous casting technique using beeswax, clay, and scrap bronze metal. Each piece is unique as the clay mould is broken during casting.',
    'BST-METAL-004',
    2150.00,
    'metalcraft',
    18,
    TRUE,
    'Budhram Baghel',
    'Kondagaon',
    'Chhattisgarh',
    'Tribal Metalcraft',
    'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    4.80
),
(
    'Kashmiri Hand-Embroidered Aari Wool Stole',
    'Fine Merino wool stole embroidered with fine aari needles capturing alpine chinars, saffron blossoms, and walnut creepers. Crafted over 3 weeks during winter isolation.',
    'KSH-WOOL-005',
    2899.00,
    'textiles',
    22,
    TRUE,
    'Ghulam Rasool Mir',
    'Budgam',
    'Jammu & Kashmir',
    'Embroidery & Shawls',
    'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    4.92
),
(
    'Madhubani Handpainted Terracotta Table Lamp',
    'Hand-molded rural terracotta base painted using bamboo nibs and natural pigment dyes depicting the sacred Tree of Life and river motifs.',
    'MDH-LAMP-006',
    1299.00,
    'painting',
    25,
    TRUE,
    'Sunita Devi (Mithila Mahila Sangh)',
    'Madhubani',
    'Bihar',
    'Folk Painting & Clay',
    'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    4.75
),
(
    'Kutch Rogan Castor Oil Art Table Runner',
    'Extremely rare 300-year-old art form where boiled castor oil paste mixed with mineral colors is drawn in mid-air using a metal stylus onto coarse cotton khadi.',
    'KUT-ROGAN-007',
    1899.00,
    'textiles',
    12,
    TRUE,
    'Khatri Rizwan',
    'Nirona',
    'Gujarat',
    'Heritage Textiles',
    'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
    4.88
),
(
    'Saharanpur Hand-Carved Sheesham Wood Jewelry Box',
    'Solid Indian rosewood box featuring delicate jaali (trellis) lattice carving and brass inlay work with a plush velvet-lined interior.',
    'SHR-WOOD-008',
    1150.00,
    'woodcraft',
    30,
    TRUE,
    'Irshad Ahmed Master Carver',
    'Saharanpur',
    'Uttar Pradesh',
    'Woodcraft & Carving',
    'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    4.79
);
