spring.application.name=fulfillx-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/fulfillx
spring.datasource.username=fulfillx
spring.datasource.password=fulfillx_dev_password

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

info.app.name=FulfillX
info.app.description=Production-style ecommerce and fulfillment platform
info.app.version=1.0.0

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] %logger{36} - %msg%n

app.jwt.secret=${JWT_SECRET:DyodAqXYU0BU5TOAG77sUnODWnzGscTjb3zn4I-eKoU}
app.jwt.expiration-ms=3600000