spring.application.name=fulfillx-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/fulfillx
spring.datasource.username=fulfillx
spring.datasource.password=fulfillx_dev_password

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info

app.jwt.secret=${JWT_SECRET:DyodAqXYU0BU5TOAG77sUnODWnzGscTjb3zn4I-eKoU}
app.jwt.expiration-ms=3600000